Repository campusdomar/PuMuKIT, pull requests merged in 2019-02, with the labels that each got.

#993 TTK-20685 change size of thumbnails generated
  app/config/encoder.yml
Labels: feature

#1000 TTK-20689 fix reload list of mmobj when sync metadata
  src/Pumukit/NewAdminBundle/Resources/views/MultimediaObject/modalsyncmetadata.html.twig
  src/Pumukit/NewAdminBundle/Resources/views/UNESCO/edit.html.twig
Labels: Hotfix

#986 TTK-20618 undo hide chat on channels
  src/Pumukit/NewAdminBundle/Controller/LiveController.php
  src/Pumukit/NewAdminBundle/Resources/views/Live/create.html.twig
  src/Pumukit/NewAdminBundle/Resources/views/Live/update.html.twig
Labels: Hotfix

#989 TTK-19032 dynamic advance catalogue
  src/Pumukit/NewAdminBundle/Controller/UNESCOController.php
  src/Pumukit/NewAdminBundle/DependencyInjection/Configuration.php
  src/Pumukit/NewAdminBundle/DependencyInjection/PumukitNewAdminExtension.php
  src/Pumukit/NewAdminBundle/Resources/views/UNESCO/index.html.twig
  src/Pumukit/NewAdminBundle/Resources/views/UNESCO/show.html.twig
Labels: feature

#1012 TTK-20182 WebTVBundle: Added analytics template to base
  src/Pumukit/WebTVBundle/Resources/views/Layout/analytics.html.twig
  src/Pumukit/WebTVBundle/Resources/views/Layout/base.html.twig
Labels: enhancement, feature
